roadiz_core:
    appNamespace: '%env(string:APP_NAMESPACE)%'
    appVersion: '%env(string:APP_VERSION)%'
    healthCheckToken: '%env(string:APP_HEALTH_CHECK_TOKEN)%'
    staticDomainName: ~
    useNativeJsonColumnType: true
    hideRoadizVersion: false
    # Force displaying translation locale in every generated node-source paths.
    # This should be enabled if you redirect users based on their language on homepage.
    forceLocale: false

    # Force displaying translation locale in generated node-source paths even if there is an url-alias in it.
    forceLocaleWithUrlAliases: false

    # When no information to find locale is found and "forceLocale" parameter is enabled,
    # Roadiz can find root path translation based on Accept-Language header.
    # Be careful if you are using a reverse-proxy cache, YOU MUST vary on Accept-Language header and normalize it.
    # @see https://varnish-cache.org/docs/6.3/users-guide/increasing-your-hitrate.html#http-vary
    useAcceptLanguageHeader: '%env(bool:APP_USE_ACCEPT_LANGUAGE_HEADER)%'

    # Use 422 constraint violation list response for contact-forms and custom-forms errors.
    # Make sure your exposed "api_custom_forms_item_post" API operation for custom-forms and "api_contact_form_post" API operation for contact-forms.
    useConstraintViolationList: true

    # Exposed API operation name for custom-forms POST
    customFormPostOperationName: api_custom_forms_item_post

    medias:
        unsplash_client_id: '%env(string:APP_UNSPLASH_CLIENT_ID)%'
        soundcloud_client_id: '%env(string:APP_SOUNDCLOUD_CLIENT_ID)%'
        google_server_id: '%env(string:APP_GOOGLE_SERVER_ID)%'
        ffmpeg_path: '%env(string:APP_FFMPEG_PATH)%'
    captcha:
        private_key: '%env(string:APP_CAPTCHA_PRIVATE_KEY)%'
        public_key: '%env(string:APP_CAPTCHA_PUBLIC_KEY)%'
        verify_url: '%env(string:APP_CAPTCHA_VERIFY_URL)%'
    inheritance:
        type: single_table
    projectLogoUrl: '%env(string:PROJECT_LOGO_URL)%'
    reverseProxyCache:
        frontend:
            default:
                host: '%env(string:VARNISH_HOST)%'
                domainName: '%env(string:VARNISH_DOMAIN)%'



