security:
    role_hierarchy:
        ROLE_BACKEND_USER:
            - ROLE_USER
            - ROLE_ACCESS_USERS_DETAIL
        ROLE_SUPERADMIN:
            - ROLE_ACCESS_ATTRIBUTES
            - ROLE_ACCESS_ATTRIBUTES_DELETE
            - ROLE_ACCESS_CUSTOMFORMS
            - ROLE_ACCESS_CUSTOMFORMS_DELETE
            - ROLE_ACCESS_CUSTOMFORMS_RETENTION
            - ROLE_ACCESS_CUSTOMFORMS_WEBHOOKS
            - ROLE_ACCESS_DOCTRINE_CACHE_DELETE
            - ROLE_ACCESS_DOCUMENTS
            - ROLE_ACCESS_DOCUMENTS_CREATION_DATE
            - ROLE_ACCESS_DOCUMENTS_DELETE
            - ROLE_ACCESS_DOCUMENTS_LIMITATIONS
            - ROLE_ACCESS_GROUPS
            - ROLE_ACCESS_LOGS
            - ROLE_ACCESS_NODES
            - ROLE_ACCESS_NODES_DELETE
            - ROLE_ACCESS_NODES_SETTING
            - ROLE_ACCESS_NODES_STATUS
            - ROLE_ACCESS_NODETYPES
            - ROLE_ACCESS_NODE_ATTRIBUTES
            - ROLE_ACCESS_REALMS
            - ROLE_ACCESS_REALM_NODES
            - ROLE_ACCESS_REDIRECTIONS
            - ROLE_ACCESS_SETTINGS
            - ROLE_ACCESS_TAGS
            - ROLE_ACCESS_TAGS_DELETE
            - ROLE_ACCESS_TRANSLATIONS
            - ROLE_ACCESS_USERS
            - ROLE_ACCESS_USERS_DELETE
            - ROLE_ACCESS_USERS_DETAIL
            - ROLE_ACCESS_VERSIONS
            - ROLE_ACCESS_WEBHOOKS
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_BACKEND_USER
